name: Backend CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Jest tests
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.2.0

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Test with Jest
        run: npm run test
        working-directory: ./backend

  docker:
    name: Build and test Docker image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t tbr-backend ./backend

      - name: Run Docker container
        run: docker run --rm -d -p 3000:3000 --name tbr-app -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -e DIRECT_URL="${{ secrets.DIRECT_URL }}" tbr-backend

      - name: Wait for server to be ready (timeout 30s)
        run: |
          echo "Waiting for server to respond on /..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:3000/; then
              exit 0
            fi
            sleep 1
          done
          echo "Server did not respond in time"
          exit 1

      - name: Stop and remove container
        if: always()
        run: |
          docker stop tbr-app || true
